Ruby on Rails capstone project - Budget app
DJ-MrJay/Money-Matters pull request #2
Opened 2023-08-11 20:12 UTC by DJ-MrJay

In this project, I implemented:
- A splash screen
- Sign up and log in pages
- A home page (categories page)
- A transactions page
- A "add a new category" page
- A "add a new transaction" page
- Created unit and integration tests
- Deployed to Render (see README)
- Made a presentation video (see README)

2023-08-11 22:33 UTC, fobadara requested changes
Hi @DJ-MrJay, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Clean code
✅ Design is very close to the template
✅ Descriptive README and PR summary

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because it is not appropriate or possible to make it an inline comment

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- I noticed that you didn't really work on the desktop screen size. It is good when your app is responsive even though it is not a requirement for this project

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 22:33 UTC, fobadara commented on app/views/devise/registrations/new.html.erb
> +</div>
[OPTIONAL] Good job including a link to the login page here but I think it would look better if it is beside the submit button on the left.

2023-08-11 22:33 UTC, fobadara commented on app/views/devise/registrations/new.html.erb
[REQUIRED] Good job with your design. It is very close to the template as requested but I need you to pay attention to some points:
- Kindly ensure that the inputs are within the same white background colour with dashes separating them
- Kindly ensure that the general background colour of the signup page is the same as the template (the colour seems grey)
- Kindly ensure that the width of the inputs container fills the entire page

![image](https://github.com/DJ-MrJay/Money-Matters/assets/62938735/a9ccdea0-c186-4017-a366-cbf4170e93c3)

2023-08-11 22:33 UTC, fobadara commented on app/views/categories/index.html.erb
[REQUIRED] Please ensure that your design follows the template in terms of colour, typography and layout. Kindly refactor your code to fit the requirements pointed out in the image below:
![image](https://github.com/DJ-MrJay/Money-Matters/assets/62938735/5452f5ca-07fd-44f7-87ca-cbaf81a5b1ce)

2023-08-11 22:33 UTC, fobadara commented on app/views/expenses/index.html.erb
[REQUIRED] Please ensure that your design follows the template in terms of colour, typography and layout. Kindly refactor your code to fit the requirements pointed out in the image below:

![image](https://github.com/DJ-MrJay/Money-Matters/assets/62938735/812f0075-0cb9-4e5d-8ae5-69b7863318b1)

2023-08-12 02:17 UTC, OLIPLICHE approved these changes
Hi @DJ-MrJay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Applied the required changes (✅)) 👏
- Followed the design guidelines👏
- The App is working fine 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-12 10:26 UTC, merged